name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
Jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v2
      with:
        node-version: "16"
      -uses: bounceapp/render-actions@0.6.0
       with: 
        render-tokens: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}} #GH token
        service-id: "srv-cioeagtph6elhbscr33g" #unique id for each app
        retries: 20
        wait: 16000
        sleep: 30000